######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 10 19:51:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . test
INCLUDEPATH += . test

# Input
HEADERS += serial.h test/global.h test/main.h
SOURCES += serial.cpp test/main.c test/main.cpp test/test.c
